Inventory
SWE-C3/Adventure-Game pull request #23
Opened 2018-11-28 10:01 UTC by MichaelLubos

Optional:
fixes #5

<description>

2018-11-28 14:14 UTC, KnutZuidema commented on Inventory.py
> +class Equipment(object):
Bitte keine Klassen nur für Datenspeicherung erstellen. Klassen sollten wenigstens eine Methode haben, die nicht der Konstruktor ist. Für reine Datenklassen eignen sich `namedtuple` sehr gut. In diesem Fall würde das so aussehen:
```python
from collections import namedtuple
Equipment = namedtuple('Equipment', ('name', 'strength'))
```

2018-11-28 14:14 UTC, KnutZuidema commented on Inventory.py
> +    def __str__(self):
Hier sollte eigentlich eine Implementierung in curses stehen, nicht nur eine Ausgabe zu einem String

2018-11-28 14:33 UTC, KnutZuidema requested changes
Die Datei sollte in snake_case benannt sein und in den Ordner `src` gelegt werden

2018-11-29 07:08 UTC, KnutZuidema requested changes
Hier der pylint output:
```
src/inventory.py:21:0: C0301: Line too long (89/79) (line-too-long)
src/inventory.py:30:0: C0305: Trailing newlines (trailing-newlines)
src/inventory.py:1:0: C0111: Missing module docstring (missing-docstring)
src/inventory.py:10:0: C0111: Missing class docstring (missing-docstring)
src/inventory.py:10:0: R0205: Class 'Inventory' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
src/inventory.py:17:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:24:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:28:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:5:0: C0411: standard import "from collections import namedtuple" should be placed before "from utility import draw_table_centered" (wrong-import-order)
```

2018-11-29 07:08 UTC, KnutZuidema commented on src/inventory.py
> +        draw_table_centered(inventory_screen, ['Name', 'Heilungsmenge'], self.items.name)
items darf keine leere Menge sein.
Ausserdem muss das Argument für `draw_table_center` eine Liste von Dicts sein. Wenn du `Item` und `Equipment` nirgendwo anders verwendest, würde ich die gar nicht definieren und einfach dicts mit den jeweiligen keys benutzen

2018-11-29 07:08 UTC, KnutZuidema commented on src/inventory.py
> +    def print(self):
Hier wird das Equipment nicht angezeigt.

2018-11-29 10:32 UTC, Heratexx commented
Hier noch die aktuellen pylint ausgaben.
src/inventory.py:27:0: C0301: Line too long (100/79) (line-too-long)
src/inventory.py:35:0: C0301: Line too long (109/79) (line-too-long)
src/inventory.py:1:0: C0111: Missing module docstring (missing-docstring)
src/inventory.py:10:0: C0111: Missing class docstring (missing-docstring)
src/inventory.py:10:0: R0205: Class 'Inventory' inherits from object, can be safely removed from bases in python3 (useless-object-inheritance)
src/inventory.py:17:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:42:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:46:4: C0111: Missing method docstring (missing-docstring)
src/inventory.py:3:0: W0611: Unused draw_table_centered imported from utility (unused-import)
src/inventory.py:5:0: C0411: standard import "from collections import namedtuple" should be placed before "from utility import draw_table_centered" (wrong-import-order)

2018-11-29 10:54 UTC, KnutZuidema commented on src/game_map.py
> +
Bitte nicht andere Dateien ändern, auch wenn autopep8 das automatisch macht. Der Pull Request sollte sich auf eine Sache beziehen

2018-11-29 12:28 UTC, KnutZuidema approved these changes

2018-11-29 12:29 UTC, merged