pause_menu
SWE-C3/Adventure-Game pull request #24
Opened 2018-11-28 10:43 UTC by PascalTruglio

Optional:
fixes #<8>

<pause_menu.rev1>

2018-11-28 14:03 UTC, KnutZuidema reviewed
Die Datei sollte in den Ordner src gelegt werden

2018-11-28 14:03 UTC, KnutZuidema commented on pause_menu.py
> +class pause_menu:
Klassennamen sollten PascalCase sein

2018-11-28 14:03 UTC, KnutZuidema commented on pause_menu.py
> +        yPosOffset = int(size[0] / 2) - 2
Integer Division funktioniert in Python mit `//`, also `size[0] // 2` statt `int(...)`

2018-11-28 14:03 UTC, KnutZuidema commented on pause_menu.py
> +sure_load_savegame = sure_load_savegame(main_screen)
in der Datei sollten nur die Klassen definiert sein, kein Code ausgeführt werden

2018-11-28 17:37 UTC, Heratexx commented on pause_menu.py
> +        self.screen.clear()
Für die Sicherheitsabfragen brauchst du keine eigenen Klassen zu definieren. Die können hier komplett raus

2018-11-28 17:39 UTC, Heratexx commented on pause_menu.py
> +    def __init__(self, screen):
Die Klassen für die Sicherheitsabfragen brauchen hier nicht rein

2018-11-28 17:39 UTC, Heratexx commented on pause_menu.py
> +    def __init__(self, screen):
Die Klassen für die Sicherheitsabfragen brauchen hier nicht rein

2018-11-28 17:41 UTC, Heratexx commented on pause_menu.py
> +        self.pressed_key = read_input(menu_item_win)
Kein Input abfangen.

2018-11-28 21:30 UTC, KnutZuidema requested changes
Hier einmal der pylint Output:
```
src/pause_menu.py:1:0: C0111: Missing module docstring (missing-docstring)
src/pause_menu.py:3:0: C0111: Missing class docstring (missing-docstring)
src/pause_menu.py:10:4: C0111: Missing method docstring (missing-docstring)
src/pause_menu.py:15:8: C0103: Variable name "yPosOffset" doesn't conform to snake_case naming style (invalid-name)
src/pause_menu.py:20:12: C0103: Variable name "yPosOffset" doesn't conform to snake_case naming style (invalid-name)
```

2018-11-28 21:30 UTC, KnutZuidema commented on src/pause_menu.py
> +class PascalCase:
Die Klasse sollte nicht `PascalCase` heissen sondern nach dem System benannt werden 😂 Also einfach `PauseMenu` oder so. PascalCase heisst nur, dass Worte in einem Namen durch Grossschreibung getrennt werden und, dass der erste Buchstabe gross ist

2018-11-28 21:32 UTC, KnutZuidema requested changes

2018-11-28 21:32 UTC, KnutZuidema commented on src/pause_menu.py
> +                size[1] / 2) - (len(item) // 2), item)
Hier ist immer noch eine Stelle wo `int(...)` statt `//` verwendet wird

2018-11-29 06:45 UTC, KnutZuidema approved these changes

2018-11-29 07:40 UTC, merged