Credits
SWE-C3/Adventure-Game pull request #27
Opened 2018-11-28 19:11 UTC by mostafakanaan

Optional:
fixes #6 

@KnutZuidema der sieht die self.team variable als list of lists statt dict. Hab also noch nicht getestet. Vorschläge?

2018-11-28 19:13 UTC, mostafakanaan commented on src/Credits.py
> +        draw_table_centered(credits_win, ['Projektmanager', 'Vertriebsmanager', 'Technologiemanager', 'Qualitätsmanager'],
Soll ich Umlaute immer ausschreiben?

2018-11-28 20:08 UTC, KnutZuidema commented on src/Credits.py
> +        draw_table_centered(credits_win, ['Projektmanager', 'Vertriebsmanager', 'Technologiemanager', 'Qualitätsmanager'],
Am besten keine Umlaute, da das Standart Windows Terminal das nicht unterstützt, auch wenn Python kein Problem damit hätte.

2018-11-28 20:10 UTC, KnutZuidema reviewed
Hier einmal der pylint output:
```
src/Credits.py:45:0: C0301: Line too long (88/79) (line-too-long)
src/Credits.py:47:0: C0301: Line too long (122/79) (line-too-long)
src/Credits.py:48:0: C0330: Wrong continued indentation (add 4 spaces).
                        self.team)
                        ^   | (bad-continuation)
src/Credits.py:1:0: C0103: Module name "Credits" doesn't conform to snake_case naming style (invalid-name)
src/Credits.py:1:0: C0111: Missing module docstring (missing-docstring)
src/Credits.py:7:0: C0111: Missing class docstring (missing-docstring)
src/Credits.py:36:4: C0111: Missing method docstring (missing-docstring)
```

2018-11-28 21:23 UTC, KnutZuidema commented
> 
> 
> Optional:
> fixes #6
> 
> @KnutZuidema der sieht die self.team variable als list of lists statt dict. Hab also noch nicht getestet. Vorschläge?

Also in deiner momentanen Implementierung ist `team` ein list of dicts. Das ist auch richtig so. Oder war das nicht deine Frage?

2018-11-29 06:58 UTC, KnutZuidema requested changes
Die Datei soll nach dem snake_case system benannt werden, also erster Buchstabe klein
Ausserdem sind ein paar Zeilen zu lang, das kannst du fixen indem du autopep8 laufen lässt.
Zusätzlich musst für das Modul, die Klasse und die Methoden und Funktionen docstrings hinzufügen. Guck dir dazu am besten mal die anderen Sachen an.
Hier der pylint output für zu lange Zeilen und docstrings:
```
src/Credits.py:8:0: C0301: Line too long (103/79) (line-too-long)
src/Credits.py:29:0: C0301: Line too long (99/79) (line-too-long)
src/Credits.py:38:0: C0301: Line too long (82/79) (line-too-long)
src/Credits.py:40:0: C0301: Line too long (82/79) (line-too-long)
src/Credits.py:42:0: C0301: Line too long (82/79) (line-too-long)
src/Credits.py:44:0: C0301: Line too long (82/79) (line-too-long)
src/Credits.py:47:0: C0301: Line too long (91/79) (line-too-long)
src/Credits.py:48:0: C0301: Line too long (93/79) (line-too-long)
src/Credits.py:49:0: C0301: Line too long (95/79) (line-too-long)
src/Credits.py:50:0: C0301: Line too long (94/79) (line-too-long)
src/Credits.py:1:0: C0111: Missing module docstring (missing-docstring)
src/Credits.py:4:0: C0111: Missing class docstring (missing-docstring)
src/Credits.py:14:4: C0111: Missing method docstring (missing-docstring)
src/Credits.py:20:4: C0111: Missing method docstring (missing-docstring)
```

2018-11-29 06:58 UTC, KnutZuidema commented on src/Credits.py
> +'''
Das ganze Ding muss raus, hier sollte nur die Klassen-/Funktionsdefinitionen stehen

2018-11-29 06:58 UTC, KnutZuidema commented on src/Credits.py
> +    def print_list(self, win, row, col, list):
bitte keine variable `list` nennen. das ist ein eingebauter python typ, den du damit überschreibst

2018-11-29 06:58 UTC, KnutZuidema commented on src/Credits.py
> +        for x in list:
ausserdem keine Variablen die nur einen Buchstaben haben. benutze hier z.B. `item` oder so etwas

2018-11-29 06:58 UTC, KnutZuidema commented on src/Credits.py
> +                row += 1
Die ganze Methode `print_list` sollte nicht auf einer Klasse definiert sein, sondern gelöst davon, da du die Klasse selbst in der Methode nicht verwendest.

2018-11-29 10:22 UTC, KnutZuidema approved these changes

2018-11-29 10:29 UTC, merged