Player
SWE-C3/Adventure-Game pull request #55
Opened 2018-12-03 21:13 UTC by mostafakanaan

Optional:
fixes #29 #30 #31 #32 

Erste Version.

2018-12-03 22:50 UTC, KnutZuidema commented on src/player.py
> +        self.position = position
Hier wird `self.position` immer auf den Wert von `position` gesetzt, auch wenn der `None` ist.  
Das könnt ihr besser so machen, dass ihr den default Wert von `position` auf `(0, 0)` setzt.

2018-12-03 22:50 UTC, KnutZuidema commented on src/player.py
> +default_health = 10  # Default health of Player
Diese Werte kann man besser als Klassen-Attribute setzen, also:
```python
class Player:
    default_health = 10
    default_strength = 5
```

2018-12-03 22:50 UTC, KnutZuidema commented on src/player.py
> +        self.position[1] = y
In Python verwendet man normalerweise keine setter, kann also raus

2018-12-03 22:50 UTC, KnutZuidema commented on src/player.py
> +            self.strength += items[i]  # .Item_strength
Siehe oben, abgesehen davon, kann man `strength` besser als `property` implementieren.
```python
@property
def strength(self):
    return self.default_strength + sum(self.items)
```
Dann muss auch oben das `self.strength` weg. Kann benutzt werden wie ein normales Attribut, aber kann nicht manuell gesetzt werden

Genauso könnte man das Leben implementieren

2018-12-05 20:19 UTC, KnutZuidema requested changes

2018-12-05 20:19 UTC, KnutZuidema commented on src/player.py
> +        self.position = position
Das funktioniert immer noch nicht. Du überschreibst den default immer

2018-12-05 20:19 UTC, KnutZuidema commented on src/player.py
> +        return self.DEFAULT_HEALTH + sum(self.items[5:8])
Wäre besser wenn du einfach Lebensitems als `self.cookies` speicherst

2018-12-05 20:19 UTC, KnutZuidema commented on src/player.py
> +        self.position[1] = y_axis
Das ist immer noch ein setter, nur mit anderem Namen. Das kann komplett raus

2018-12-05 21:31 UTC, Tobi-Rook commented on src/player.py
> +        return self.DEFAULT_HEALTH + sum(self.items[5:8])
Lebenspunkte können auch nach einem Monsterkampf abgezogen werden. Die lassen sich also nicht nur durch den Default-Wert und die Cookies berechnen.

2018-12-06 13:15 UTC, KnutZuidema approved these changes

2018-12-11 11:59 UTC, merged