Item class
SWE-C3/Adventure-Game pull request #57
Opened 2018-12-05 13:14 UTC by timgo13

Optional:
fixes #<issue_id>

<description>

2018-12-05 20:28 UTC, KnutZuidema requested changes

2018-12-05 20:28 UTC, KnutZuidema commented on src/items.py
> +        self.name = name
In Python definiert man normalerweise keine setter. Kann raus. Stattdessen setzt du den Wert im Konstruktor, bzw einfach über `item.name = 'new_name'` wenn du ihn wann anders setzen musst. Gleiches gilt für die Unterklassen

2018-12-05 20:28 UTC, KnutZuidema commented on src/items.py
> +        set_random_name()
Diese Funktion kannst du so nicht aufrufen, da sie eine Methode der Unterklassen ist.

2018-12-05 21:16 UTC, timgo13 commented on src/items.py
> +        set_random_name()
Bei meinen Tests hatte das so funktioniert, hat mich aber auch erst gewundert

2018-12-11 12:02 UTC, KnutZuidema requested changes

2018-12-11 12:02 UTC, KnutZuidema commented on src/game_map.py
> +    def refresh(self, window, player):
Diese Datei sollte gar nicht verändert werden.

2018-12-11 12:37 UTC, KnutZuidema commented on src/items.py
> +        with open("items.json", "r") as read_file:
Dieser `open` Aufruf wird mit der Ordnerstruktur wie sie ist, nicht funktionieren. Ich hatte das selbe Problem und habe es gelöst indem ich immer den absoluten Pfad zu der Ressourcendatei angebe
```python
from os.path import join, abspath, dirname
with open(join(dirname(abspath(__file__)), '..', 'resources', 'items.json')) as items:
```

2018-12-17 00:37 UTC, KnutZuidema commented on src/items.py
> +    def to_string(self):
Wofür wird eine string representation benötigt? 
Davon abgesehen implementiert man die Methode `__str__` bzw. `__repr__` wenn man dies für eine Klasse machen will

2018-12-17 00:37 UTC, KnutZuidema commented on src/items.py
> +        self.type = Enum("Type", "Weapon Helmet Body Pants Shoes")
Sollte das nicht auf einen bestimmten Typen gesetzt werden durch einen Konstruktor Parameter, statt auf den Typen des Enums?

2018-12-17 13:53 UTC, timgo13 commented on src/items.py
> +    def to_string(self):
Michael wollte eine string methode für das item event haben

2018-12-17 13:55 UTC, timgo13 commented on src/items.py
> +        self.type = Enum("Type", "Weapon Helmet Body Pants Shoes")
Also sage ich vor der init dass das Attribute vom Typ Enum ist?

2018-12-22 10:15 UTC, KnutZuidema commented on src/items.py
> +    def to_string(self):
OK, dann aber bitte per `__str__`. Dann kann man einfach `str(item)` aufrufen und hat eine String Representation

2018-12-25 22:19 UTC, KnutZuidema approved these changes

2019-01-07 15:11 UTC, merged