Here comes the pull request.
SWE-C3/Adventure-Game pull request #59
Opened 2018-12-05 15:20 UTC by Oschmann

Optional:
fixes #<issue_id>

<description>

2018-12-05 15:25 UTC, KnutZuidema requested changes

2018-12-05 15:25 UTC, KnutZuidema commented on src/story.py
> +        self.pressed_key = read_input(story_win)
Es sollte am Ende kein Input abgefragt werden, jeweils vorerst nicht

2018-12-05 15:25 UTC, KnutZuidema commented on src/story.py
> +    return window.getch()
Diese Methode ist nicht noetig, sollte entfernt werden

2018-12-05 15:25 UTC, KnutZuidema commented on src/story.py
> +        self.pressed_key = ord('z')
Es muss kein key in der Klasse gespeichert werden

2018-12-05 15:25 UTC, KnutZuidema commented on src/story.py
> +        self.screen.clear()
Der Screen sollte nicht am Anfang gecleart werden, das kann im Zusammenhang mit anderen Views zu Problemen fuehren

2018-12-05 20:42 UTC, KnutZuidema requested changes

2018-12-05 20:42 UTC, KnutZuidema commented on levelfile.txt
> ++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Wäre ganz schön, wenn Pull Requests immer nur zu einem Thema sind. Also für die Levels einen eigenen auf machen. Kann ich jetzt aber auch erstmal so machen. Allerdings sollte der levelfile, in den Ordner `resources` gelegt werden

2018-12-11 12:05 UTC, KnutZuidema commented on levelfile.txt
> ++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Macht ihr das noch noch? Dann kann ich mergen

2018-12-13 11:29 UTC, Oschmann commented on levelfile.txt
> ++-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
Habe das gerade gemacht. :)

2018-12-13 11:44 UTC, KnutZuidema approved these changes

2018-12-14 19:43 UTC, merged